// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: cases.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const createCase = `-- name: CreateCase :one
INSERT INTO cases (client_id, number, title, description, court, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, client_id, number, title, description, court, status, created_at, updated_at
`

type CreateCaseParams struct {
	ClientID    uuid.UUID
	Number      string
	Title       string
	Description string
	Court       string
	Status      string
}

func (q *Queries) CreateCase(ctx context.Context, arg CreateCaseParams) (Case, error) {
	row := q.db.QueryRowContext(ctx, createCase,
		arg.ClientID,
		arg.Number,
		arg.Title,
		arg.Description,
		arg.Court,
		arg.Status,
	)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Court,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCaseByID = `-- name: GetCaseByID :one
SELECT id, client_id, number, title, description, court, status, created_at, updated_at FROM cases
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCaseByID(ctx context.Context, id uuid.UUID) (Case, error) {
	row := q.db.QueryRowContext(ctx, getCaseByID, id)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Court,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCaseByNumber = `-- name: GetCaseByNumber :one
SELECT id, client_id, number, title, description, court, status, created_at, updated_at FROM cases
WHERE number = $1
LIMIT 1
`

func (q *Queries) GetCaseByNumber(ctx context.Context, number string) (Case, error) {
	row := q.db.QueryRowContext(ctx, getCaseByNumber, number)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Court,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCaseStatus = `-- name: UpdateCaseStatus :exec
UPDATE cases
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateCaseStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateCaseStatus(ctx context.Context, arg UpdateCaseStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCaseStatus, arg.ID, arg.Status)
	return err
}
