// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: clients.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const countClients = `-- name: CountClients :one
SELECT COUNT(*) FROM clients
WHERE ($1 IS NULL OR name ILIKE '%' || $1 || '%')
  AND ($2 IS NULL OR cpf = $2)
`

type CountClientsParams struct {
	Name interface{}
	Cpf  interface{}
}

func (q *Queries) CountClients(ctx context.Context, arg CountClientsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countClients, arg.Name, arg.Cpf)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClient = `-- name: CreateClient :one
INSERT INTO clients (name, cpf, email, phone)
VALUES ($1, $2, $3, $4)
RETURNING id, name, cpf, email, phone, created_at, updated_at
`

type CreateClientParams struct {
	Name  string
	Cpf   string
	Email string
	Phone string
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, createClient,
		arg.Name,
		arg.Cpf,
		arg.Email,
		arg.Phone,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cpf,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientByCPF = `-- name: GetClientByCPF :one
SELECT id, name, cpf, email, phone, created_at, updated_at FROM clients
WHERE cpf = $1
LIMIT 1
`

func (q *Queries) GetClientByCPF(ctx context.Context, cpf string) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByCPF, cpf)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cpf,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, name, cpf, email, phone, created_at, updated_at FROM clients
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetClientByID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cpf,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
