// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: contracts.sql

package postgres

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createContract = `-- name: CreateContract :one
INSERT INTO contracts (client_id, case_id, title, description, type, amount, start_date, end_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, client_id, case_id, title, description, type, amount, start_date, end_date, active, created_at, updated_at
`

type CreateContractParams struct {
	ClientID    uuid.UUID
	CaseID      uuid.UUID
	Title       string
	Description sql.NullString
	Type        string
	Amount      string
	StartDate   time.Time
	EndDate     sql.NullTime
}

func (q *Queries) CreateContract(ctx context.Context, arg CreateContractParams) (Contract, error) {
	row := q.db.QueryRowContext(ctx, createContract,
		arg.ClientID,
		arg.CaseID,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.Amount,
		arg.StartDate,
		arg.EndDate,
	)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CaseID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Amount,
		&i.StartDate,
		&i.EndDate,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContractByID = `-- name: GetContractByID :one
SELECT id, client_id, case_id, title, description, type, amount, start_date, end_date, active, created_at, updated_at FROM contracts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetContractByID(ctx context.Context, id uuid.UUID) (Contract, error) {
	row := q.db.QueryRowContext(ctx, getContractByID, id)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CaseID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Amount,
		&i.StartDate,
		&i.EndDate,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

	const updateContract = `-- name: UpdateContract :one
UPDATE contracts
SET title = $2, description = $3, type = $4, amount = $5, start_date = $6, end_date = $7, active = $8, updated_at = NOW()
WHERE id = $1
RETURNING id, client_id, case_id, title, description, type, amount, start_date, end_date, active, created_at, updated_at
`

type UpdateContractParams struct {
	ID          uuid.UUID
	Title       string
	Description sql.NullString
	Type        string
	Amount      string
	StartDate   time.Time
	EndDate     sql.NullTime
	Active      bool
}

func (q *Queries) UpdateContract(ctx context.Context, arg UpdateContractParams) (Contract, error) {
	row := q.db.QueryRowContext(ctx, updateContract,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.Amount,
		arg.StartDate,
		arg.EndDate,
		arg.Active,
	)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CaseID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Amount,
		&i.StartDate,
		&i.EndDate,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContractsByCaseID = `-- name: ListContractsByCaseID :many
SELECT id, client_id, case_id, title, description, type, amount, start_date, end_date, active, created_at, updated_at FROM contracts
WHERE case_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListContractsByCaseID(ctx context.Context, caseID uuid.UUID) ([]Contract, error) {
	rows, err := q.db.QueryContext(ctx, listContractsByCaseID, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contract
	for rows.Next() {
		var i Contract
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.CaseID,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.Amount,
			&i.StartDate,
			&i.EndDate,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
