// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: documents.sql

package postgres

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (case_id, name, description, type, file_name, mime_type, file_size, storage_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, case_id, name, description, type, file_name, mime_type, file_size, storage_key, created_at, updated_at
`

type CreateDocumentParams struct {
	CaseID      uuid.UUID
	Name        string
	Description sql.NullString
	Type        string
	FileName    string
	MimeType    string
	FileSize    int64
	StorageKey  string
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.CaseID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.FileName,
		arg.MimeType,
		arg.FileSize,
		arg.StorageKey,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.FileName,
		&i.MimeType,
		&i.FileSize,
		&i.StorageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, case_id, name, description, type, file_name, mime_type, file_size, storage_key, created_at, updated_at FROM documents
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.FileName,
		&i.MimeType,
		&i.FileSize,
		&i.StorageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocumentsByCaseID = `-- name: ListDocumentsByCaseID :many
SELECT id, case_id, name, description, type, file_name, mime_type, file_size, storage_key, created_at, updated_at FROM documents
WHERE case_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListDocumentsByCaseID(ctx context.Context, caseID uuid.UUID) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByCaseID, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.FileName,
			&i.MimeType,
			&i.FileSize,
			&i.StorageKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
