// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: hearings.sql

package postgres

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createHearing = `-- name: CreateHearing :one
INSERT INTO hearings (case_id, title, description, type, location, scheduled_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, case_id, title, description, type, location, scheduled_at, created_at, updated_at
`

type CreateHearingParams struct {
	CaseID      uuid.UUID
	Title       string
	Description sql.NullString
	Type        string
	Location    string
	ScheduledAt time.Time
}

func (q *Queries) CreateHearing(ctx context.Context, arg CreateHearingParams) (Hearing, error) {
	row := q.db.QueryRowContext(ctx, createHearing,
		arg.CaseID,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.Location,
		arg.ScheduledAt,
	)
	var i Hearing
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Location,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHearingByID = `-- name: GetHearingByID :one
SELECT id, case_id, title, description, type, location, scheduled_at, created_at, updated_at FROM hearings
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetHearingByID(ctx context.Context, id uuid.UUID) (Hearing, error) {
	row := q.db.QueryRowContext(ctx, getHearingByID, id)
	var i Hearing
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Location,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHearingsByCaseID = `-- name: ListHearingsByCaseID :many
SELECT id, case_id, title, description, type, location, scheduled_at, created_at, updated_at FROM hearings
WHERE case_id = $1
ORDER BY scheduled_at ASC
`

func (q *Queries) ListHearingsByCaseID(ctx context.Context, caseID uuid.UUID) ([]Hearing, error) {
	rows, err := q.db.QueryContext(ctx, listHearingsByCaseID, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hearing
	for rows.Next() {
		var i Hearing
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.Location,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
