// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: timeline.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createTimelineEvent = `-- name: CreateTimelineEvent :one
INSERT INTO timeline_events (case_id, type, description, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, case_id, type, description, metadata, created_at
`

type CreateTimelineEventParams struct {
	CaseID      uuid.UUID
	Type        string
	Description string
	Metadata    pqtype.NullRawMessage
}

func (q *Queries) CreateTimelineEvent(ctx context.Context, arg CreateTimelineEventParams) (TimelineEvent, error) {
	row := q.db.QueryRowContext(ctx, createTimelineEvent,
		arg.CaseID,
		arg.Type,
		arg.Description,
		arg.Metadata,
	)
	var i TimelineEvent
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.Type,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getTimelineByCaseID = `-- name: GetTimelineByCaseID :many
SELECT id, case_id, type, description, metadata, created_at FROM timeline_events
WHERE case_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetTimelineByCaseID(ctx context.Context, caseID uuid.UUID) ([]TimelineEvent, error) {
	rows, err := q.db.QueryContext(ctx, getTimelineByCaseID, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimelineEvent
	for rows.Next() {
		var i TimelineEvent
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.Type,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
